<?php
require_once __DIR__ . '/../core/Database.php';
require_once __DIR__ . '/../core/Security.php';

class InstallController {
    
    // Path to the configuration file we will generate
    private $configFile = __DIR__ . '/../config/env.php';

    /**
     * POST /api/install
     * Handles the full installation process.
     */
    public function install() {
        // 1. SECURITY: Check if already installed
        if (file_exists($this->configFile)) {
            // Double check by trying to connect and finding users
            // If the file exists, we assume the system is configured to prevent overwriting
            http_response_code(403);
            echo json_encode(['error' => 'Application is already installed. (Config file exists)']);
            exit;
        }

        // 2. Parse Input
        $input = json_decode(file_get_contents('php://input'), true);
        
        if (!$input) {
            http_response_code(400);
            echo json_encode(['error' => 'Invalid JSON input']);
            exit;
        }

        // 3. Validate Database Credentials (Test Connection)
        try {
            $dsn = "pgsql:host=" . $input['db_host'] . ";dbname=" . $input['db_name'];
            $pdo = new PDO($dsn, $input['db_user'], $input['db_pass']);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        } catch (PDOException $e) {
            http_response_code(400);
            echo json_encode(['error' => 'Database connection failed: ' . $e->getMessage()]);
            exit;
        }

        // 4. Validate Admin Inputs
        if (!filter_var($input['admin_email'], FILTER_VALIDATE_EMAIL)) {
            http_response_code(400);
            echo json_encode(['error' => 'Invalid admin email address']);
            exit;
        }

        if (strlen($input['admin_password']) < 8) {
            http_response_code(400);
            echo json_encode(['error' => 'Admin password must be at least 8 characters']);
            exit;
        }

        // 5. Generate Configuration Content
        // We generate a secure random key for internal encryption (Stripe keys, etc)
        $appKey = bin2hex(random_bytes(32)); 

        $configContent = "<?php\n";
        $configContent .= "/**\n * ClarityStack Environment Configuration\n * Generated by Installer on " . date('Y-m-d H:i:s') . "\n */\n\n";
        $configContent .= "return [\n";
        $configContent .= "    'DB_HOST' => '" . addslashes($input['db_host']) . "',\n";
        $configContent .= "    'DB_NAME' => '" . addslashes($input['db_name']) . "',\n";
        $configContent .= "    'DB_USER' => '" . addslashes($input['db_user']) . "',\n";
        $configContent .= "    'DB_PASS' => '" . addslashes($input['db_pass']) . "',\n";
        $configContent .= "    'APP_KEY' => '" . $appKey . "',\n";
        $configContent .= "    'DEBUG'   => false\n";
        $configContent .= "];\n";

        // 6. Begin Installation Transaction
        try {
            // Step A: Write Config File
            $configDir = dirname($this->configFile);
            if (!is_dir($configDir)) {
                if (!mkdir($configDir, 0750, true)) {
                    throw new Exception("Could not create config directory. Check permissions.");
                }
            }
            
            if (file_put_contents($this->configFile, $configContent) === false) {
                throw new Exception("Could not write config file. Check permissions.");
            }

            // Step B: Import Schema
            // We read the schema.sql file located in the database directory
            $schemaPath = __DIR__ . '/../../../database/schema.sql';
            if (!file_exists($schemaPath)) {
                throw new Exception("Schema file not found at: " . $schemaPath);
            }
            
            $sql = file_get_contents($schemaPath);
            
            // Execute the schema to create tables
            $pdo->exec($sql);

            // Step C: Configure System Settings
            // We manually construct the JSON blocks for the settings table
            
            $publicConfig = json_encode([
                'logo_url' => filter_var($input['logo_url'] ?? '', FILTER_SANITIZE_URL),
                'primary_color' => $this->validateHex($input['primary_color'] ?? '#3b82f6'),
                'support_email' => filter_var($input['support_email'] ?? '', FILTER_VALIDATE_EMAIL),
                'no_reply_email' => filter_var($input['no_reply_email'] ?? 'no-reply@localhost', FILTER_VALIDATE_EMAIL),
                'link_timeout' => (int)($input['link_timeout'] ?? 10)
            ]);

            // We need to use the newly generated key to encrypt secrets immediately
            // Since we can't easily inject the key into the static Security class without reloading,
            // we will simulate the encryption here or manually instantiate a helper if preferred.
            // For simplicity in this script, we assume Core\Security handles its key injection via the Config/Env we just wrote,
            // but since that file is not "required" by the running script yet, we have to be careful.
            
            // Safer approach for Installer: Store empty encrypted values now, admin updates later via Dashboard.
            // Or, implement a temporary encryptor using the $appKey we just generated.
            $privateConfig = json_encode([
                'stripe_secret' => '', // User must set later or we add simple encryption logic here
                'smtp_host' => '',
                'smtp_user' => '',
                'smtp_pass' => ''
            ]);

            $stmtSettings = $pdo->prepare("
                INSERT INTO settings (business_name, public_config, private_config, is_installed) 
                VALUES (:name, :pub, :priv, TRUE)
            ");
            
            $stmtSettings->execute([
                ':name' => strip_tags($input['business_name']),
                ':pub'  => $publicConfig,
                ':priv' => $privateConfig
            ]);

            // Step D: Create Super Admin User
            $passwordHash = password_hash($input['admin_password'], PASSWORD_ARGON2ID);
            
            $stmtAdmin = $pdo->prepare("
                INSERT INTO users (email, password_hash, role, created_at) 
                VALUES (:email, :pass, 'admin', NOW())
            ");
            
            $stmtAdmin->execute([
                ':email' => $input['admin_email'],
                ':pass'  => $passwordHash
            ]);

            // Step E: Seed Initial CMS Page (Home)
            // Ensures the site isn't blank upon first visit
            $defaultHomeBlocks = json_encode([
                [
                    "type" => "hero", 
                    "props" => [
                        "title" => "Welcome to " . strip_tags($input['business_name']),
                        "subtitle" => "Photography & Creative Studio"
                    ]
                ],
                [
                    "type" => "text_simple",
                    "props" => [
                        "content" => "<p>This is your new homepage. Log in to the Admin Dashboard to customize this text, upload photos, and manage your bookings.</p>"
                    ]
                ]
            ]);

            $stmtPage = $pdo->prepare("
                INSERT INTO pages (slug, title, blocks, is_published) 
                VALUES ('home', 'Home', :blocks, TRUE)
            ");
            
            $stmtPage->execute([':blocks' => $defaultHomeBlocks]);

            // Installation Complete
            echo json_encode([
                'status' => 'success',
                'message' => 'Installation completed successfully. You may now log in.'
            ]);

        } catch (Exception $e) {
            // Attempt cleanup: remove config file if it was created but DB setup failed
            if (file_exists($this->configFile)) {
                @unlink($this->configFile);
            }
            
            http_response_code(500);
            echo json_encode(['error' => 'Installation failed: ' . $e->getMessage()]);
        }
    }

    /**
     * Helper to validate Hex Color codes
     */
    private function validateHex($color) {
        if (preg_match('/^#[a-f0-9]{6}$/i', $color)) {
            return $color;
        }
        return '#3b82f6'; // Default Blue
    }
}
?>
