<?php
require_once __DIR__ . '/../core/Database.php';
require_once __DIR__ . '/../core/Security.php';

class InstallController {
    
    // Path to the configuration file we will generate
    private $configFile = __DIR__ . '/../config/env.php';

    /**
     * POST /api/install
     * Handles the full installation process.
     */
    public function install() {
        // 0. ENVIRONMENT: Fail-fast Sanity Check
        try {
            $this->checkRequirements();
        } catch (Exception $e) {
            http_response_code(500); // Internal Server Error (Environment Issue)
            echo json_encode(['error' => $e->getMessage()]);
            exit;
        }

        // 1. SECURITY: Check if already installed
        if (file_exists($this->configFile)) {
            // Double check by trying to connect and finding users
            // If the file exists, we assume the system is configured to prevent overwriting
            http_response_code(403);
            echo json_encode(['error' => 'Application is already installed. (Config file exists)']);
            exit;
        }

        // 2. Parse Input
        $input = json_decode(file_get_contents('php://input'), true);
        
        if (!$input) {
            http_response_code(400);
            echo json_encode(['error' => 'Invalid JSON input']);
            exit;
        }

        // 3. Validate Database Credentials (Test Connection)
        try {
            $dsn = "pgsql:host=" . $input['db_host'] . ";dbname=" . $input['db_name'];
            $pdo = new PDO($dsn, $input['db_user'], $input['db_pass']);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        } catch (PDOException $e) {
            http_response_code(400);
            echo json_encode(['error' => 'Database connection failed: ' . $e->getMessage()]);
            exit;
        }

        // 4. Validate Admin Inputs
        if (!filter_var($input['admin_email'], FILTER_VALIDATE_EMAIL)) {
            http_response_code(400);
            echo json_encode(['error' => 'Invalid admin email address']);
            exit;
        }

        if (strlen($input['admin_password']) < 8) {
            http_response_code(400);
            echo json_encode(['error' => 'Admin password must be at least 8 characters']);
            exit;
        }

        // 5. Generate Configuration Content
        // We generate a secure random key for internal encryption (Stripe keys, etc)
        $appKey = bin2hex(random_bytes(32)); 

        $configContent = "<?php\n";
        $configContent .= "/**\n * ClarityStack Environment Configuration\n * Generated by Installer on " . date('Y-m-d H:i:s') . "\n */\n\n";
        $configContent .= "return [\n";
        $configContent .= "    'DB_HOST' => '" . addslashes($input['db_host']) . "',\n";
        $configContent .= "    'DB_NAME' => '" . addslashes($input['db_name']) . "',\n";
        $configContent .= "    'DB_USER' => '" . addslashes($input['db_user']) . "',\n";
        $configContent .= "    'DB_PASS' => '" . addslashes($input['db_pass']) . "',\n";
        $configContent .= "    'APP_KEY' => '" . $appKey . "',\n";
        $configContent .= "    'DEBUG'   => false\n";
        $configContent .= "];\n";

        // 6. Begin Installation Transaction
        try {
            // Start Transaction to ensure atomicity
            if (!$pdo->beginTransaction()) {
                throw new Exception("Could not start database transaction.");
            }

            // Step A: Write Config File
            $configDir = dirname($this->configFile);
            if (!is_dir($configDir)) {
                if (!mkdir($configDir, 0750, true)) {
                    throw new Exception("Could not create config directory. Check permissions.");
                }
            }
            
            if (file_put_contents($this->configFile, $configContent) === false) {
                throw new Exception("Could not write config file. Check permissions.");
            }

            // Step B: Import Schema
            // We read the schema.sql file located in the database directory
            $schemaPath = __DIR__ . '/../../../database/schema.sql';
            if (!file_exists($schemaPath)) {
                throw new Exception("Schema file not found at: " . $schemaPath);
            }
            
            $sql = file_get_contents($schemaPath);
            
            // Execute the schema to create tables
            $pdo->exec($sql);

            // Step C: Configure System Settings
            // We manually construct the JSON blocks for the settings table
            
            $publicConfig = json_encode([
                'logo_url' => filter_var($input['logo_url'] ?? '', FILTER_SANITIZE_URL),
                'primary_color' => $this->validateHex($input['primary_color'] ?? '#3b82f6'),
                'support_email' => filter_var($input['support_email'] ?? '', FILTER_VALIDATE_EMAIL),
                'no_reply_email' => filter_var($input['no_reply_email'] ?? 'no-reply@localhost', FILTER_VALIDATE_EMAIL),
                'link_timeout' => (int)($input['link_timeout'] ?? 10)
            ]);

            // We need to use the newly generated key to encrypt secrets immediately
            // Since we can't easily inject the key into the static Security class without reloading,
            // we will simulate the encryption here using the generated $appKey.
            $encrypt = function($data) use ($appKey) {
                if (empty($data)) return '';

                $ivLength = openssl_cipher_iv_length('aes-256-cbc');
                $iv = random_bytes($ivLength);
                $encrypted = openssl_encrypt($data, 'aes-256-cbc', $appKey, 0, $iv);
                return base64_encode($encrypted . '::' . $iv);
            };
            
            // Store encrypted values (empty if not provided)
            $privateConfig = json_encode([
                'stripe_secret' => $encrypt($input['stripe_secret'] ?? ''),
                'smtp_host' => $encrypt($input['smtp_host'] ?? ''),
                'smtp_user' => $encrypt($input['smtp_user'] ?? ''),
                'smtp_pass' => $encrypt($input['smtp_pass'] ?? '')
            ]);

            $stmtSettings = $pdo->prepare("
                INSERT INTO settings (business_name, public_config, private_config, is_installed) 
                VALUES (:name, :pub, :priv, TRUE)
            ");
            
            $stmtSettings->execute([
                ':name' => strip_tags($input['business_name']),
                ':pub'  => $publicConfig,
                ':priv' => $privateConfig
            ]);

            // Step D: Create Super Admin User
            $passwordHash = password_hash($input['admin_password'], PASSWORD_ARGON2ID);
            
            $stmtAdmin = $pdo->prepare("
                INSERT INTO users (email, password_hash, role, created_at) 
                VALUES (:email, :pass, 'admin', NOW())
            ");
            
            $stmtAdmin->execute([
                ':email' => $input['admin_email'],
                ':pass'  => $passwordHash
            ]);

            // Step E: Seed Initial CMS Page (Home)
            // Ensures the site isn't blank upon first visit
            $defaultHomeBlocks = json_encode([
                [
                    "type" => "hero", 
                    "props" => [
                        "title" => "Welcome to " . strip_tags($input['business_name']),
                        "subtitle" => "Photography & Creative Studio"
                    ]
                ],
                [
                    "type" => "text_simple",
                    "props" => [
                        "content" => "<p>This is your new homepage. Log in to the Admin Dashboard to customize this text, upload photos, and manage your bookings.</p>"
                    ]
                ]
            ]);

            $stmtPage = $pdo->prepare("
                INSERT INTO pages (slug, title, blocks, is_published) 
                VALUES ('home', 'Home', :blocks, TRUE)
            ");
            
            $stmtPage->execute([':blocks' => $defaultHomeBlocks]);

            // Commit transaction
            $pdo->commit();

            // Installation Complete
            echo json_encode([
                'status' => 'success',
                'message' => 'Installation completed successfully. You may now log in.'
            ]);

        } catch (Exception $e) {
            // Rollback if active transaction
            if ($pdo->inTransaction()) {
                $pdo->rollBack();
            }

            // Attempt cleanup: remove config file if it was created but DB setup failed
            if (file_exists($this->configFile)) {
                @unlink($this->configFile);
            }
            
            http_response_code(500);
            echo json_encode(['error' => 'Installation failed: ' . $e->getMessage()]);
        }
    }

    /**
     * Helper to validate Hex Color codes
     */
    private function validateHex($color) {
        if (preg_match('/^#[a-f0-9]{6}$/i', $color)) {
            return $color;
        }
        return '#3b82f6'; // Default Blue
    }

    /**
     * Checks if the server environment meets the requirements.
     * Throws Exception if requirements are not met.
     */
    private function checkRequirements() {
        // 1. Check PHP Version (Require 8.1+)
        if (version_compare(PHP_VERSION, '8.1.0', '<')) {
            throw new Exception('PHP 8.1 or higher is required. Current version: ' . PHP_VERSION);
        }

        // 2. Check Required Extensions
        $requiredExtensions = ['pdo', 'pdo_pgsql', 'json', 'mbstring', 'filter', 'ctype', 'session'];
        $missing = [];
        foreach ($requiredExtensions as $ext) {
            if (!extension_loaded($ext)) {
                $missing[] = $ext;
            }
        }
        if (!empty($missing)) {
            throw new Exception('Missing required PHP extensions: ' . implode(', ', $missing));
        }

        // 3. Check Directory Permissions (Config must be writable)
        // If config dir doesn't exist, check parent
        $configDir = dirname($this->configFile);
        if (!file_exists($configDir)) {
             // Check if parent of config dir is writable to create it
             $parent = dirname($configDir);
             if (!is_writable($parent)) {
                 throw new Exception("Parent directory is not writable: $parent");
             }
        } else {
             if (!is_writable($configDir)) {
                 throw new Exception("Config directory is not writable: $configDir");
             }
        }
    }
}
?>
